[[resources-movement-order]]
== Movements
A `Movement` is a manual move of a `TransportUnit` from a `Location` A to `Location` B. It always refers to a `TransportUnit` and not to any
kind of material or articles. A `Movement` has a *source* `Location` where the `TransportUnit` is picked up and may have a *target*
`Location` or in general a target `LocationGroup` where to bring the `TransportUnit` to. A `Movement` is meant to be executed by a human
user in manual warehouses with some kind of equipment, like a fork lift, a trolley etc. So the `TransportUnit` is either on a `Location` or
on the equipment - the latter is also expressed with a `Location`. That said, a `Movement` changed the source `Location` where it is picked
up or dropped off but has no assignment to the human user. The operator/user may change, but the `TransportUnit` is still assigned to the
`Location` it is currently on.

[[movement-index]]
=== Movement Index
The index with all possible operations on `Movements` can be retrieved with a GET request:

include::{generated}/move-index/http-request.adoc[]

The response lists all the operations possible on `Movements` with a name and the corresponding href link:

include::{generated}/move-index/http-response.adoc[]

[[movement-create]]
=== Create a Movement
To create a new `Movement` a client needs to send a `POST` request to `Movements` sub resource of the primary
`TransportUnits` resource with the required data in the request body. The required data must contain the source where to
pick up the `TransportUnit` and the target where to drop it. The `TransportUnit` that shall be moved is directly
referenced as the primary resource in the URI.

include::{generated}/move-create/http-request.adoc[]

If the `Movement` has been created successfully, the server returns the URI to the created resource:

include::{generated}/move-create/http-response.adoc[]

[[movement-findForStateAndTypesAndSource]]
=== Find all Movements
A HTTP `GET` request to the primary resource without any query parameters returns an array of all existing `Movements`.

include::{generated}/move-find-all/http-request.adoc[]

Returns in this example an array of three `Movements` or an empty array if none exist:

include::{generated}/move-find-all/http-response.adoc[]

[[movement-findForStateAndTypesAndSource]]
=== Find Movements
A HTTP `GET` request to the primary resource with additional query parameters is required to find `Movements` in a
particular `state`, `type` and `source`.

include::{generated}/order-find-all/http-request.adoc[]

Returns an array of `Movements` or an empty array:

include::{generated}/order-find-all/http-response.adoc[]

[[movement-move]]
=== Move a Movement
An already existing `Movement` can be moved from one `Location` to another. The client needs to send a HTTP `PATCH`
request to the identified resource and pass a subset of a `Movement` in the request body.

The request could look like this:
include::{generated}/move-move/http-request.adoc[]

If the `Movement` has been moved successfully, the server returns the updated representation of the `Movement` as part
of the response body:
include::{generated}/move-move/http-response.adoc[]

But if the `Movement` to be moved is already completed the server rejects the operation and responds with:
include::{generated}/move-move-with-completed/http-response.adoc[]

[[movement-cancel]]
=== Cancel a Movement
An existing `Movement` can be cancelled by a client. Therefore a `DELETE` request needs to be sent to the `Movement`
resource. Cancellation is not always supported and depends on the current state of the `Movement`. In the standard
implementation a `Movement` can only be cancelled if the state is not already `CANCELLED` or higher, otherwise an
exception is thrown.

The request could look like this:
include::{generated}/move-cancel/http-request.adoc[]

If the `Movement` has been cancelled, the server returns the order as part of the response body:
include::{generated}/move-cancel/http-response.adoc[]

[[movement-complete]]
=== Complete a Movement
To complete a `Movement` a client needs to explicitly send the `COMPLETE` action along a `POST` request to the
`Movement` resource. This completes the `Movement` and sets the target to the required `target` that is passed from the
caller in the response body.

A valid request looks like:
include::{generated}/move-complete/http-request.adoc[]

Whereas the server responds on success:
include::{generated}/move-complete/http-response.adoc[]
