[[resources-receiving-order]]
== Movements
A `Movement` is a manual move of a `TransportUnit` from a `Location` A to `Location` B. It always refers to a `TransportUnit` and not to any
kind of material or articles. A `Movement` has a *source* `Location` where the `TransportUnit` is picked up and may have a *target*
`Location` or in general a target `LocationGroup` where to bring the `TransportUnit` to. A `Movement` is meant to be executed by a human
user in manual warehouses with some kind of equipment, like a fork lift, a trolley etc. So the `TransportUnit` is either on a `Location` or
on the equipment - the latter is also expressed with a `Location`. That said, a `Movement` changed the source `Location` where it is picked
up or dropped off but has no assignment to the human user. The operator/user may change, but the `TransportUnit` is still assigned to the
`Location` it is currently on.

[[movement-index]]
=== Movement Index
The index with all possible operations on a `Movements` can be retrieved with a GET request:

include::{generated}/get-move-index/http-request.adoc[]

The response lists all the operations possible on `Movements` with a name and the corresponding href link:

include::{generated}/get-move-index/http-response.adoc[]

[[movement-create]]
=== Create a Movement
To place a `Movement` a client must send a `POST` request to `movements` sub resource of the primary `transport-units` resource with the
required data in the request body. The required data contains the source where to pick up the `TransportUnit` and the target where to drop
it. The `TransportUnit` that shall be moved is directly referenced as the primary resource in the URI.

include::{generated}/move-create/http-request.adoc[]

If the `Movement` has been created successfully, the server returns the URI to the created resource:

include::{generated}/move-create/http-response.adoc[]

[[movement-findForStateAndTypesAndSource]]
=== Find Movements
A HTTP GET request to the primary resource is required to find all `ReceivingOrders`.

include::{generated}/order-find-all/http-request.adoc[]

Returns an array of `ReceivingOrders` or an empty array:

include::{generated}/order-find-all/http-response.adoc[]

[[movement-move]]
=== Move a Movement
An earlier posted `ReceivingOrder` can be cancelled for further processing. The client needs to send a HTTP DELETE request with the unique
identifier of the order.

include::{generated}/order-cancel/http-request.adoc[]

If the `ReceivingOrder` has been cancelled, the server returns the order as part of the response body:

include::{generated}/order-cancel/http-response.adoc[]

In case the order couldn't be cancelled because the order is already in process or has been processed, the server responds with:

include::{generated}/order-cancel-403/http-response.adoc[]

[[movement-complete]]
=== Complete a Movement
To complete a `Movement` a client needs to explicitly send the `COMPLETE` action to the `Movement` resource. This completes the `Movement`
and sets the target to the required `target` that is passed from the caller in the response body.

include::{generated}/order-complete/http-response.adoc[]
